# == In this configuration you setup Alchemy´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: heading
  hint: true
  contents:
  - name: title
    type: EssenceText
    default: :heading_title
  - name: subtitle
    type: EssenceText
    default: :heading_subtitle
  - name: summary
    type: EssenceRichtext
    default: :heading_summary

- name: timeline_item
  contents:
  - name: period
    type: EssenceText
    default: :timeline_item_period
  - name: icon
    type: EssenceText
    default: 'graduation-cap'
  - name: picture
    type: EssencePicture
  - name: title
    type: EssenceText
    default: :timeline_item_title
  - name: subtitle
    type: EssenceText
    default: :timeline_item_subtitle
  - name: description
    type: EssenceRichtext
    default: :timeline_item_description
