# == This file defines the page layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: index
  unique: true
  elements: [heading]
  autogenerate: [heading]

- name: experiences
  unique: false
  elements: [heading, timeline_item]
  autogenerate: [heading, timeline_item]
